### ISSUE TITLE
Overlapping of cells and bad positioning of wires

### ISSUE THREAD

**Issue by SimonForest** [smimram/satex#1]
The following example 
```latex
\documentclass{standalone}
\usepackage{satex}

\deftwocell[rectangle,"="]{eq1to2 : 1 -> 2}
\deftwocell[rectangle,"="]{eq2to2 : 2 -> 2}
\deftwocell["AAA"]{cnode : 2 -> 0}

\begin{document}
$ \twocell{
  (label["A"]* label["A"] * label["A"])
  *
  (eq1to2 * eq2to2)
  *
  (label["A"] * label["A"] * label["A","A"])
  *
  (1 * cnode * 1)
  *
  (eq2to2)
  *
  (label["A","A"])
} $
\end{document}
```
produces the following output : [pb.pdf](https://github.com/smimram/satex/files/8177188/pb.pdf)

As can be seen on the pdf, there are several unexpected behaviors on the output: 
- the two "=" cells at the top are overlapping
- the wires of two "=" cells are not well-positioned
- the circle around "AAA" is not big enough

I am not sure if I am missing an option or not, but I would have assumed that not having these issues would have been the default behavior.

**Comment by smimram** [comment]
I have fixed the overlapping boxes. The rest can be fixed as follows:
```
\documentclass{standalone}
\usepackage{satex}

\deftwocell[rectangle,"="]{eq1to2 : 1 -> 2}
\deftwocell[rectangle,"="]{eq2to2 : 2 -> 2}
\deftwocell["AAA",width=1.6]{cnode : 2 -> 0}

\begin{document}
$ \twocell{
  (label["A","A","A"])
  *
  (eq1to2 * eq2to2)
  *
  (label["A","A","A","A"])
  *
  (1 * cnode * 1)
  *
  (eq2to2)
  *
  (1 * space2 * 1)
  *
  (label["A","A"])
} $
\end{document}
```
[Here is the output](https://github.com/smimram/satex/files/8177927/bug1.pdf).

- for the size of the circle, I don't think I have an easy consistent way to predict the size of the label, so that this has to be enforced manually,
- for the spacing between the wires at the bottom, I fear some problems if I force the rightmost wire to be right, so that I think manual spacing is fine here (but I am open to suggestions).

**Comment by SimonForest** [comment]
Great, thanks!

For the size of the circle, is it not possible to ask LaTeX to give you the dimensions of the label's box when using `\deftwocell` and output this information to the .satex so that satex is able to adjust automatically? This would require a more sophisticated definition of `\deftwocell` though…
